animationsData = 
{
    -- Saucer = {{Name = "Idle", Source = gfx.imagetable.new("images/enemy_saucer"), Delay = 50, Loop = true}},
    BulletBlackhole = {{Name = "Idle", Source = gfx.imagetable.new("images/bullets/bullet_blackhole"), Delay = 20, Loop = true}},
    BulletPlasma = {{Name = "Idle", Source = gfx.imagetable.new("images/bullets/bullet_plasma"), Delay = 20, Loop = true}},
    BulletSerpentine = {{Name = "Idle", Source = gfx.imagetable.new("images/bullets/bullet_serpentine"), Delay = 20, Loop = true}},
    BulletExplosion = {{Name = "Idle", Source = gfx.imagetable.new("images/bullets/bullet_explosion"), Delay = 20, Loop = false}},
    BulletFlamethrower = {{Name = "Idle", Source = gfx.imagetable.new("images/bullets/bullet_shotgun"), Delay = 20, Loop = false}},
    BulletToxicVape = {{Name = "Idle", Source = gfx.imagetable.new("images/bullets/bullet_toxicVape"), Delay = 20, Loop = true}},
    AnimationHit = {{Name = "Idle", Source = gfx.imagetable.new("images/fx/hit_01"), Delay = 20, Loop = false}},
    Saucer = {},
    Xwing = {},
    EnemyLargeOne = {{Name = "Idle", Source = gfx.imagetable.new("images/enemies/large/enemy_large_01"), Delay = 20, Loop = true}},
    EnemyLargeTwo = {{Name = "Idle", Source = gfx.imagetable.new("images/enemies/large/enemy_large_02"), Delay = 20, Loop = true}},
    EnemyLargeThree = {{Name = "Idle", Source = gfx.imagetable.new("images/enemies/large/enemy_large_03"), Delay = 20, Loop = true}},
    EnemyLargeFour = {{Name = "Idle", Source = gfx.imagetable.new("images/enemies/large/enemy_large_04"), Delay = 20, Loop = true}},

    MainMenu = {Name = "Idle", Source = gfx.imagetable.new("images/ui/menus/main_menu"), Delay = 20, Loop = true},
    SelectionScreen = {Name = "Idle", Source = gfx.imagetable.new("images/ui/menus/selection_screen"), Delay = 20, Loop = true},
    ShopBackground = {Name = "Idle", Source = gfx.imagetable.new("images/ui/menus/shop_background"), Delay = 20, Loop = true},
    EndScreen = {Name = "Idle", Source = gfx.imagetable.new("images/ui/menus/end_screen"), Delay = 20, Loop = true},
    AchievementPanel = {Name = "Idle", Source = gfx.imagetable.new("images/ui/menus/achievement_panel"), Delay = 20, Loop = true},
    MenuOpen = {Name = "Idle", Source = gfx.imagetable.new("images/ui/anim_transition"), Delay = 33, Loop = false},
    MenuClose = {Name = "Idle", Source = gfx.imagetable.new("images/ui/anim_transition_reverse"), Delay = 33, Loop = false},
}
