shopItemsData = 
{
    -- unlock, cost, level, levelMax, multiplyer
    ShopItem("Speed Up",UnlockPassive("Speed Up", gfx.image.new("images/ui/icons/projectileSpeed"), "", nil, getUpgradePassive("projectileSpeedBonus"), "+20% Projectile Speed"),100, 0, 5, 1.5),
    ShopItem("Scale Up",UnlockPassive("Scale Up", gfx.image.new("images/ui/icons/projectileScale"), "", nil, getUpgradePassive("scaleBonus"), "+10% Projectile Scale"),100, 0, 5, 1.5),
    ShopItem("Damage Up",UnlockPassive("Damage Up", gfx.image.new("images/ui/icons/damageUp"), "", nil, getUpgradePassive("damageBonus"), "+20% Damage Bonus"),100, 0, 5, 1.5),
    ShopItem("HP Up",table.findByParam(unlocksData, "name","HP Up"),300, 0, 5, 2),
    ShopItem("Cooldown-",table.findByParam(unlocksData, "name","Cooldown-"),400, 0, 5, 1.5),
    ShopItem("XP+",table.findByParam(unlocksData, "name","XP+"),750, 0, 5, 1.5),
    ShopItem("Regeneration",table.findByParam(unlocksData, "name","Regeneration"),500, 0, 5, 1.5),
    ShopItem("Duration",table.findByParam(unlocksData, "name","Duration"),300, 0, 5, 1.5),
    ShopItem("Life Up",table.findByParam(unlocksData, "name","Life Up"),1000, 0, 5, 2),
    ShopItem("Shield",table.findByParam(unlocksData, "name","Shield"),250, 0, 5, 1.5),
    ShopItem("Reroll",table.findByParam(unlocksData, "name","Reroll"),350, 0, 5, 1.5),
    ShopItem("Omni",table.findByParam(unlocksData, "name","Omni"),1500, 0, 1, 1.5),
    ShopItem("Laser",table.findByParam(unlocksData, "name","Laser"),2000, 0, 1, 1.5),
    ShopItem("Orbiter",table.findByParam(unlocksData, "name","Orbiter"),2000, 0, 1, 1.5),
    ShopItem("Shotgun",table.findByParam(unlocksData, "name","Shotgun"),2000, 0, 1, 1.5),
    ShopItem("Launcher",table.findByParam(unlocksData, "name","Launcher"),3000, 0, 1, 1.5),
    ShopItem("Plasma",table.findByParam(unlocksData, "name","Plasma"),3000, 0, 1, 1.5),
    ShopItem("Artillery",table.findByParam(unlocksData, "name","Artillery"),4000, 0, 1, 1.5),
    ShopItem("Cosmic",table.findByParam(unlocksData, "name","Cosmic"),4000, 0, 1, 1.5),
    ShopItem("Defender",table.findByParam(unlocksData, "name","Defender"),4000, 0, 1, 1.5),
    ShopItem("Reflecting",table.findByParam(unlocksData, "name","Reflecting"),4000, 0, 1, 1.5),
    ShopItem("Tactical",table.findByParam(unlocksData, "name","Tactical"),4000, 0, 1, 1.5),
    ShopItem("Wide",table.findByParam(unlocksData, "name","Wide"),4000, 0, 1, 1.5),
}