unlocksData = 
{
    -- name, image, description, condition, upgrade, cost, level, levelMax, multiplyer
    UnlockWeapon("Shockwave", gfx.image.new("images/ui/icons/shockwave"), "Kill 100 enemies", Condition("enemiesKilled", 100,true), table.findByParam(upgradesData, "type", "Shockwave"),"Wide projectiles that pushes back enemies"),
    UnlockWeapon("Guided", gfx.image.new("images/ui/icons/guided"), "Kill 1000 enemies", Condition("enemiesKilled", 1000,true), table.findByParam(upgradesData, "type", "Guided"),"Auto-guided bullets"),
    UnlockWeapon("Aura", gfx.image.new("images/ui/icons/aura"), "Kill 3000 enemies", Condition("enemiesKilled", 3000, true), table.findByParam(upgradesData, "type", "Aura"),"Zone that damages enemies inside"),
    UnlockWeapon("ToxicVape", gfx.image.new("images/ui/icons/toxicVape"), "Kill 5000 enemies", Condition("enemiesKilled", 5000,true), table.findByParam(upgradesData, "type", "ToxicVape"),"Slow projectiles that poisons enemies, applying damage over time"),
    UnlockWeapon("Blackhole", gfx.image.new("images/ui/icons/blackHole"), "Kill 10000 enemies", Condition("enemiesKilled", 10000, true), table.findByParam(upgradesData, "type", "Blackhole"),"Attracts enemies at its center"),
    UnlockWeapon("BeamReflect", gfx.image.new("images/ui/icons/beamReflect"), "Kill 15000 enemies", Condition("enemiesKilled", 15000, true), table.findByParam(upgradesData, "type", "BeamReflect"),"Auto-targeting reflective Colt bullet"),
    UnlockWeapon("Beam", gfx.image.new("images/ui/icons/beam"), "Clear Deep Space 1", conditionMapCleared(1), table.findByParam(upgradesData, "type", "Beam"),"Linear laser"),
    UnlockWeapon("LaserDome", gfx.image.new("images/ui/icons/laserDome"), "Clear Deep Space 2", conditionMapCleared(2), table.findByParam(upgradesData, "type", "LaserDome"),"Laser line that roams the screen"),
    UnlockWeapon("Plasma", gfx.image.new("images/ui/icons/plasma"), "Clear Deep Space 3", conditionMapCleared(3), table.findByParam(upgradesData, "type", "Plasma"),"Pass-through electric orbs that bounce on walls"),
    UnlockWeapon("Rocket", gfx.image.new("images/ui/icons/rocket"), "Clear Orbit 1", conditionMapCleared(4), table.findByParam(upgradesData, "type", "Rocket"),"Shoots a rocket with exploses in AOE damage"),
    UnlockWeapon("Freezer", gfx.image.new("images/ui/icons/freezer"), "Clear Orbit 2", conditionMapCleared(5), table.findByParam(upgradesData, "type", "Freezer"),"Laser that freezes enemies"),
    UnlockWeapon("Orbital", gfx.image.new("images/ui/icons/orbital"), "Clear Orbit 3", conditionMapCleared(6), table.findByParam(upgradesData, "type", "Orbital"),"3 shots burst rotating bullets"),
    UnlockWeapon("Drone", gfx.image.new("images/ui/icons/droneLaser"), "Clear City 1", conditionMapCleared(7), table.findByParam(upgradesData, "type", "Drone"),"Rotating drone that shoots lasers"),
    UnlockWeapon("Tracer", gfx.image.new("images/ui/icons/tracer"), "Clear City 2", conditionMapCleared(8), table.findByParam(upgradesData, "type", "Tracer"),"Laser bouncing on walls"),
    UnlockWeapon("Wiper", gfx.image.new("images/ui/icons/wiper"), "Clear City 3", conditionMapCleared(9), table.findByParam(upgradesData, "type", "Wiper"),"Instantly damages all enemies"),
    UnlockPassive("Cooldown-", gfx.image.new("images/ui/icons/cooldown"), "Clear Deep Space 3", conditionMapCleared(3), getUpgradePassive("attackSpeedBonus"), "-10% Weapons Cooldown",250, 0, 5, 1.5),
    UnlockPassive("Regeneration", gfx.image.new("images/ui/icons/regen"), "Clear Orbit 3", conditionMapCleared(6), getUpgradePassive("regenerationRate"),"+20% Regeneration Rate",250, 0, 5, 1.5),
    UnlockPassive("Omni", gfx.image.new("images/ui/icons/omni"), "Clear City 3", conditionMapCleared(9), getUpgradePassiveByName("omni"),"+5% Weapons Damage, Cooldown, Scale And Speed",1000, 0, 1, 1.5),
    UnlockPassive("HP Up", gfx.image.new("images/ui/icons/hpMax"), "Level up 15 times", Condition("level", 15, true), getUpgradePassive("hpMax"),"+5 HP",500, 0, 5, 1.5),
    UnlockPassive("XP+", gfx.image.new("images/ui/icons/xpUp"), "Level up 30 times", Condition("level", 30, true), getUpgradePassive("xpBonus"), "+20% XP Gain",1000, 0, 5, 2),
    UnlockPassive("Reroll", gfx.image.new("images/ui/icons/rerolls"), "Level up 50 times", Condition("level", 50, true), getUpgradePassive("rerolls"),"+5 Rerolls",500, 0, 5, 1.5),
    UnlockPassive("Armor", gfx.image.new("images/ui/icons/shield"), "Level up 70 times", Condition("level", 70, true), getUpgradePassive("shield"),"-1 Damage Taken",250, 0, 5, 1.5),
    UnlockPassive("Duration", gfx.image.new("images/ui/icons/duration"), "Level up 100 times", Condition("level", 100, true), getUpgradePassive("durationBonus"),"+20% Weapons Duration",100, 0, 5, 1.5),
    UnlockPassive("Life Up", gfx.image.new("images/ui/icons/lifeUp"), "Level up 150 times", Condition("level", 150, true), getUpgradePassive("lives"),"+1 Life (Resurection)",10000, 0, 5, 2),
    UnlockCannon("Beam Cannon", gfx.image.new("images/player/cannons/cannon_beam"), "Reach level 5 with Beam", ConditionWeaponLevel("Beam", 5), table.findByParam(cannonsData, "id", "beam"),"Starter Weapon : Beam",100, 0, 5, 1.5),
    UnlockCannon("Orbital Cannon", gfx.image.new("images/player/cannons/cannon_orbital"), "Reach level 5 with Orbital", ConditionWeaponLevel("Orbital", 5), table.findByParam(cannonsData, "id", "orbital"),"Starter Weapon : Orbital",100, 0, 5, 1.5),
    UnlockCannon("Rocket Cannon", gfx.image.new("images/player/cannons/cannon_rocket"), "Reach level 5 with Rocket", ConditionWeaponLevel("Rocket", 5), table.findByParam(cannonsData, "id", "rocket"),"Starter Weapon : Rocket",100, 0, 5, 1.5),
    UnlockCannon("Plasma Cannon", gfx.image.new("images/player/cannons/cannon_plasma"), "Reach level 5 with Plasma", ConditionWeaponLevel("Plasma", 5), table.findByParam(cannonsData, "id", "plasma"),"Starter Weapon : Plasma",100, 0, 5, 1.5),
    UnlockCannon("Shotgun Cannon", gfx.image.new("images/player/cannons/cannon_shotgun"), "Reach level 5 with Shotgun", ConditionWeaponLevel("Flamethrower", 5), table.findByParam(cannonsData, "id", "shotgun"),"Starter Weapon : Shotgun",100, 0, 5, 1.5),
}