unlocksData = 
{
    -- name, image, description, condition, upgrade, cost, level, levelMax, multiplyer
    UnlockWeapon("Aura", gfx.image.new("images/ui/icons/aura"), "Kill 30 enemies", Condition("enemiesKilled", 30), table.findByParam(weaponsData, "className", "Aura"),"Zone that damages enemies when inside"),
    UnlockWeapon("Wiper", gfx.image.new("images/ui/icons/wiper"), "Kill 50 enemies", Condition("enemiesKilled", 50), table.findByParam(weaponsData, "className", "Wiper"),"Inflicts damage every X seconds"),
    UnlockWeapon("BeamReflect", gfx.image.new("images/ui/icons/BeamReflect"), "Kill 50 enemies", Condition("enemiesKilled", 50), table.findByParam(weaponsData, "className", "BeamReflect"),"Reflective Colt bullet"),
    UnlockWeapon("Freezer", gfx.image.new("images/ui/icons/freezer"), "Kill 50 enemies", Condition("enemiesKilled", 50), table.findByParam(weaponsData, "className", "Freezer"),"Freezes enemies"),
    UnlockWeapon("Blackhole", gfx.image.new("images/ui/icons/blackHole"), "Kill 75 enemies", Condition("enemiesKilled", 75), table.findByParam(weaponsData, "className", "Blackhole"),"Attracts enemies at its center"),
    UnlockWeapon("Drone", gfx.image.new("images/ui/icons/droneLaser"), "Kill 90 enemies", Condition("enemiesKilled", 90), table.findByParam(weaponsData, "className", "Drone"),"Releases rotating lasers when an enemy is hit"),
    UnlockWeapon("Flamethrower", gfx.image.new("images/ui/icons/flamethrower"), "Kill 110 enemies", Condition("enemiesKilled", 110), table.findByParam(weaponsData, "className", "Flamethrower"),"Continously damages enemies inside its cone"),
    UnlockWeapon("Guided", gfx.image.new("images/ui/icons/guided"), "Kill 130 enemies", Condition("enemiesKilled", 130), table.findByParam(weaponsData, "className", "Guided"),"Auto-guided weapons"),
    UnlockWeapon("LaserDome", gfx.image.new("images/ui/icons/laserDome"), "Kill 150 enemies", Condition("enemiesKilled", 150), table.findByParam(weaponsData, "className", "LaserDome"),"Laser wall that protects the base"),
    UnlockWeapon("Orbital", gfx.image.new("images/ui/icons/orbital"), "Kill 170 enemies", Condition("enemiesKilled",170), table.findByParam(weaponsData, "className", "Orbital"),"Rotating bullets"),
    UnlockWeapon("Serpentine", gfx.image.new("images/ui/icons/serpentine"), "Kill 190 enemies", Condition("enemiesKilled", 190), table.findByParam(weaponsData, "className", "Serpentine"),"Sinusoidal piercing bullets"),
    UnlockWeapon("Shockwave", gfx.image.new("images/ui/icons/shockwave"), "Kill 210 enemies", Condition("enemiesKilled", 210), table.findByParam(weaponsData, "className", "Shockwave"),"Pushes back enemies"),
    UnlockWeapon("ToxicVape", gfx.image.new("images/ui/icons/toxicVape"), "Kill 230 enemies", Condition("enemiesKilled", 230), table.findByParam(weaponsData, "className", "ToxicVape"),"Poisons enemies and dot HP"),
    UnlockWeapon("Tracer", gfx.image.new("images/ui/icons/tracer"), "Kill 250 enemies", Condition("enemiesKilled", 250), table.findByParam(weaponsData, "className", "Tracer"),"Laser bouncing on walls"),
    UnlockPassive("Cooldown-", gfx.image.new("images/ui/icons/cooldown"), "Reach Level 5", Condition("level", 5), getUpgradePassive("attackSpeedBonus"), "-10% Weapons Cooldown",100, 0, 5, 1.5),
    UnlockPassive("XP+", gfx.image.new("images/ui/icons/xpUp"), "Reach Level 10", Condition("level", 10), getUpgradePassive("xpBonus"), "+10% XP Gain",100, 0, 5, 1.5),
    UnlockPassive("Regeneration", gfx.image.new("images/ui/icons/regen"), "Reach Level 10", Condition("level", 10), getUpgradePassive("regenerationRate"),"+10% Regeneration Rate",100, 0, 5, 1.5),
    UnlockPassive("Duration", gfx.image.new("images/ui/icons/duration"), "Reach Level 15", Condition("level", 15), getUpgradePassive("durationBonus"),"+10% Weapons Duration",100, 0, 5, 1.5),
    UnlockPassive("Life Up", gfx.image.new("images/ui/icons/lifeUp"), "Reach Level 15", Condition("level", 15), getUpgradePassive("lives"),"+1 Life (Resurection)",100, 0, 5, 1.5),
    UnlockPassive("Shield", gfx.image.new("images/ui/icons/shield"), "Reach Level 20", Condition("level", 20), getUpgradePassive("shield"),"-1 Damage Taken",100, 0, 5, 1.5),
    UnlockPassive("Reroll", gfx.image.new("images/ui/icons/rerolls"), "Reach Level 20", Condition("level", 20), getUpgradePassive("rerolls"),"+5 Rerolls",100, 0, 5, 1.5),
    UnlockPassive("Omni", gfx.image.new("images/ui/icons/omni"), "Reach Level 30", Condition("level", 30), getUpgradePassiveByName("omni"),"+4% Weapons Damage, Cooldown, Scale And Speed",100, 0, 1, 1.5),
    UnlockCannon("Laser", gfx.image.new("images/player/cannons/cannon_beam"), "Reach level 5 with beam", ConditionWeaponLevel("Beam", 1), table.findByParam(cannonsData, "id", "beam"),"Starter Weapon : Beam",100, 0, 1, 1.5),
    UnlockCannon("Orbiter", gfx.image.new("images/player/cannons/cannon_orbital"), "Reach level 5 with orbital", ConditionWeaponLevel("Orbital", 5), table.findByParam(cannonsData, "id", "orbital"),"Starter Weapon : Orbital",100, 0, 1, 1.5),
    UnlockCannon("Launcher", gfx.image.new("images/player/cannons/cannon_rocket"), "Reach level 5 with rocket", ConditionWeaponLevel("Rocket", 5), table.findByParam(cannonsData, "id", "rocket"),"Starter Weapon : Rocket",100, 0, 1, 1.5),
}